# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from __future__ import unicode_literals
from ..interfaces import MathMorphoMask


def test_MathMorphoMask_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='%s',
    mandatory=True,
    position=0,
    ),
    intensity_threshold=dict(argstr='-t %s',
    ),
    out_file=dict(argstr='%s',
    keep_extension=True,
    name_source='in_file',
    name_template='%s_morpho_mask',
    position=1,
    ),
    volume_threshold=dict(argstr='-v %s',
    ),
    )
    inputs = MathMorphoMask.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_MathMorphoMask_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = MathMorphoMask.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
